// SPDX-FileCopyrightText: 2026 Frans van Dorsselaer
//
// SPDX-License-Identifier: GPL-3.0-only

#include "stdafx.h"

#include "device.h"
#include "trace.h"
#include "device.tmh"

#include "public.h"
#include "queue.h"


static EVT_WDF_DEVICE_PREPARE_HARDWARE DevicePrepareHardware;
#pragma alloc_text(PAGE, DevicePrepareHardware)
_Use_decl_annotations_
static NTSTATUS DevicePrepareHardware(WDFDEVICE Device, WDFCMRESLIST ResourceList, WDFCMRESLIST ResourceListTranslated) {
    UNREFERENCED_PARAMETER(ResourceList);
    UNREFERENCED_PARAMETER(ResourceListTranslated);
    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Entry");

    PDEVICE_CONTEXT deviceContext;
    deviceContext = DeviceGetContext(Device);

    if (deviceContext->UsbDevice == NULL) {
        WDF_USB_DEVICE_CREATE_CONFIG createParameters;
        WDF_USB_DEVICE_CREATE_CONFIG_INIT(&createParameters, USBD_CLIENT_CONTRACT_VERSION_602);

        NTSTATUS status = WdfUsbTargetDeviceCreateWithParameters(Device, &createParameters, WDF_NO_OBJECT_ATTRIBUTES, &deviceContext->UsbDevice);
        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfUsbTargetDeviceCreateWithParameters failed %!STATUS!", status);
            return status;
        }
    }

    //
    // Select the first configuration of the device, using the first alternate setting of each interface
    //
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS configParameters;
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS_INIT_MULTIPLE_INTERFACES(&configParameters, 0, NULL);
    NTSTATUS status = WdfUsbTargetDeviceSelectConfig(deviceContext->UsbDevice, WDF_NO_OBJECT_ATTRIBUTES, &configParameters);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "WdfUsbTargetDeviceSelectConfig failed %!STATUS!", status);
        return status;
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Exit");

    return STATUS_SUCCESS;
}


#pragma alloc_text(PAGE, StubCreateDevice)
_Use_decl_annotations_
NTSTATUS StubCreateDevice(WDFDRIVER Driver, PWDFDEVICE_INIT DeviceInit) {
    static DECLARE_CONST_UNICODE_STRING(securityDescriptor, L"D:P(A;;GA;;;SY)(A;;GA;;;BA)(A;;GR;;;AU)(A;;GX;;;WD)");

    UNREFERENCED_PARAMETER(Driver);
    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DEVICE, "%!FUNC! Entry");

    WdfDeviceInitSetCharacteristics(DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);

    NTSTATUS status = WdfDeviceInitAssignSDDLString(DeviceInit, &securityDescriptor);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "%!FUNC! WdfDeviceInitAssignSDDLString failed %!STATUS!", status);
        return status;
    }

    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    pnpPowerCallbacks.EvtDevicePrepareHardware = DevicePrepareHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    WDFDEVICE device;
    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "%!FUNC! WdfDeviceCreate failed %!STATUS!", status);
        return status;
    }

    PDEVICE_CONTEXT deviceContext;
    deviceContext = DeviceGetContext(device);
    deviceContext->PrivateDeviceData = 0;

    status = WdfDeviceCreateDeviceInterface(device, &GUID_DEVINTERFACE_USBIPD_STUB, NULL);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "%!FUNC! WdfDeviceCreateDeviceInterface failed %!STATUS!", status);
        return status;
    }

    status = StubQueueInitialize(device);
    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE, "%!FUNC! StubQueueInitialize failed %!STATUS!", status);
        return status;
    }

    return STATUS_SUCCESS;
}
