# SPDX-FileCopyrightText: 2026 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build
    runs-on: windows-2025-vs2026

    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
        with:
          msbuild-architecture: x64

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          cache: true
          cache-dependency-path: |
            global.json
            '**/packages.lock.json'

      - name: Restore dependencies
        run: |
          msbuild -target:Restore

      - name: Build x64 Drivers
        run: |
          msbuild -maxCpuCount -property:Configuration=Release -property:Platform=x64 -binaryLogger:LogFile=build-x64.binlog

      - name: Build arm64 Drivers
        run: |
          msbuild -maxCpuCount -property:Configuration=Release -property:Platform=ARM64 -binaryLogger:LogFile=build-arm64.binlog

      - name: MakeCab x64
        run: |
          makecab /D arch=x64 /f .\c\windows-attestation.ddf

      - name: MakeCab arm64
        run: |
          makecab /D arch=arm64 /f .\c\windows-attestation.ddf

      - name: Upload windows-attestation-x64
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: x64/Release/windows-attestation-x64.cab
          archive: false

      - name: Upload windows-attestation-arm64
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ARM64/Release/windows-attestation-arm64.cab
          archive: false

      - name: Upload Full Debug Symbols
        id: upload-debug
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: full-debug-symbols
          path: |
            x64/Release/UsbipdHubFilter.pdb
            x64/Release/UsbipdStub.pdb
            ARM64/Release/UsbipdHubFilter.pdb
            ARM64/Release/UsbipdStub.pdb

      - name: GitHub Attestation for windows-attestation-*.cab
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: '*/Release/windows-attestation-*.cab'

      - name: GitHub Attestation for Debug Symbols
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-name: full-debug-symbols.zip
          subject-digest: sha256:${{ steps.upload-debug.outputs.artifact-digest }}

      - name: Submit Dependencies to GitHub
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: advanced-security/component-detection-dependency-submission-action@31f25a8de68ae5ce2ca274bc28546a78683c15ce # v0.1.4
        with:
          detectorArgs: MSBuildBinaryLog=Enable
          detectorsFilter: MSBuildBinaryLog

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: always
