# SPDX-FileCopyrightText: 2026 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    name: Build
    runs-on: windows-2025-vs2026

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
        with:
          msbuild-architecture: x64

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          cache: true
          cache-dependency-path: |
            global.json
            '**/packages.lock.json'

      - name: Restore dependencies
        run: |
          msbuild -target:Restore

      - name: Build x64 Drivers
        run: |
          msbuild -maxCpuCount -property:Configuration=Release -property:Platform=x64 -binaryLogger:LogFile=build-x64.binlog

      - name: Build arm64 Drivers
        run: |
          msbuild -maxCpuCount -property:Configuration=Release -property:Platform=ARM64 -binaryLogger:LogFile=build-arm64.binlog

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: |
            x64/Release/*/*
            ARM64/Release/*/*

      - name: Build Attestation
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-name: artifacts.zip
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}

      - name: Submit Dependencies to GitHub
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: advanced-security/component-detection-dependency-submission-action@9c110eb34dee187cd9eca76a652b9f6a0ed22927 # v0.1.1
        with:
          detectorArgs: MSBuildBinaryLog=Enable
          detectorsFilter: MSBuildBinaryLog

      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: always
