# SPDX-FileCopyrightText: 2026 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: windows-2025-vs2026

    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0
      with:
        msbuild-architecture: x64

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        cache: true
        cache-dependency-path: |
          global.json
          '**/packages.lock.json'

    - name: Restore dependencies
      run: |
        msbuild /t:Restore

    - name: Build x64 Drivers
      run: |
        msbuild /m /p:Configuration=Release /p:Platform=x64

    - name: Build arm64 Drivers
      run: |
        msbuild /m /p:Configuration=Release /p:Platform=ARM64

    - name: Upload Artifacts
      id: upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: artifacts
        path: |
          x64/Release/*/*
          ARM64/Release/*/*

# NOTE: Enable once repository is public
#     - name: Build Attestation
#       uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
#       with:
#         subject-name: artifacts.zip
#         subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
